### ISSUE TITLE
Progress > 100% on Homepage active collectives

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-frontend#621]
![screen shot 2018-07-25 at 18 45 58](https://user-images.githubusercontent.com/806/43214923-0cc997b4-903b-11e8-992a-fab29108c3ae.png)

**Comment by xdamman** [comment]
It's not unusual to see on crowdfunding sites projects that are over their goal. But we should probably show a different text or color or something. 
@cuiki any thoughts?

**Comment by znarf** [comment]
@xdamman ok, If you think it's fine, we can close it.

**Comment by xdamman** [comment]
let's wait on @cuiki's feedback

**Comment by cuiki** [comment]
This is the case when a collective has only one goal, correct? If it had a second goal it should automatically focus on the next goal (we should probably encourage users to create more than one budget goal).

For the case of just one goal, there is a case in saying that showing a completed goal in the context of the card might not be a good idea since we could of kill the notion of 'recurring support'. I think we should show something else.

Let me think it through for bit, I'll get back with something.

**Comment by znarf** [comment]
Stale. Closing.
